-- CreateTable
CREATE TABLE "mesasDisponibles" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "nombre" TEXT NOT NULL,
    "precioHora" INTEGER NOT NULL
);

-- CreateTable
CREATE TABLE "ventaProductos" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "producto" TEXT NOT NULL,
    "precio" REAL NOT NULL,
    "fecha" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- CreateTable
CREATE TABLE "ventaMesas" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "mesa" TEXT NOT NULL,
    "fecha" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "venta" REAL NOT NULL
);
